### PR TITLE
Resolved issue #16

### PR DESCRIPTION
**Pull request by subhadeepCh**
Resolved error at line **616 in app.js**
Resolved error at line **236 in index.ejs**

Reason of the error :
properties of undefined object was being rendered --- most probably because the database was empty and this condition was not handled.

Conclusion : Error fixed and has no problem at run
@harshit9270 @AMAN123956

### CODE REVIEW

**Review by heysujal — APPROVED** [review]

**Comment by subhadeepCh** [comment]
@heysujal @AMAN123956 Also resolved branch conflict, now you can merge the pull request

**Review by heysujal — APPROVED** [review]

**Comment by heysujal** [comment]
@subhadeepCh There is a conflict and please check the code again. There is duplicate code present in your code.

**Comment by subhadeepCh** [comment]
@heysujal I have again resolved the conflicts, Please check

**Comment by subhadeepCh** [comment]
@heysujal Hey i have resolved the conflicts again, Please do check.

**Comment by subhadeepCh** [comment]
@heysujal @me-harshit @AMAN123956 Please review and merge my pull request

**Comment by harshit9270** [comment]
You have changed more than 1370 lines and total less than 10 lines of useful code.
Too hard to understand.

**Pull request closed without merging**
